### ISSUE TITLE
feedback/feedforward

### ISSUE THREAD

**Issue by KoopReynders** [nadiachaja/fix-the-flow-interactive-website#4]
Geef de verschillende onderdelenvan de story-pagina een titel en korte uitleg, zodat een gebruiker weet waar die naar kijkt.

> Don’t worry about stating the obvious…the obvious almost never is.
zegt Joshua Porter
https://principles.design/examples/principles-of-user-interface-design

**Comment by nadiachaja** [comment]
ik heb boven de selects een tekst geschreven wat je kan gaan doen met de selects 
https://github.com/nadiachaja/fix-the-flow-interactive-website/blob/2179dfb5ae51d09586b5001ba251f136ca203a9e/lessons/lessons.html#L137

**Comment by KoopReynders** [comment]
Dat is precies de bedoeling Nadia. Goed gedaan. Nu weet een gebruiker wat die kan doen. 
De feedback met het gevonden aantal stories staat nog niet mooi uitgelijnd. 
Zou ook mooi zijn om in deze feedback ook de filters mee te nemen, bijvoorbeeld `5 stories gevonden met de filter 'penguin' en 'autumn'`

<img width="707" alt="image" src="https://github.com/user-attachments/assets/f52fbd83-bba4-4082-8fe7-4c8db1f5c654" />

(je kan beter 'jij wil' in plaats van 'jij wilt' schrijven, zonder t is  informeler en past daarom beter bij 'jij')
