### ISSUE TITLE
Feedback filter systeem

### ISSUE THREAD

**Issue by KoopReynders** [nadiachaja/fix-the-flow-interactive-website#5]
Geef de gebruiker feedback over de zoek-resultaten als die de filter heeft gebruikt, bv
"Er zijn 4 pinguïn resultaten in het engels"

**Comment by nadiachaja** [comment]
ik heb nu dat je kan zien hoeveel stories er zijn gevonden 
https://github.com/nadiachaja/fix-the-flow-interactive-website/blob/2179dfb5ae51d09586b5001ba251f136ca203a9e/lessons/lessons.html#L182

https://github.com/nadiachaja/fix-the-flow-interactive-website/blob/2179dfb5ae51d09586b5001ba251f136ca203a9e/lessons/lessons.js#L134
https://github.com/nadiachaja/fix-the-flow-interactive-website/blob/2179dfb5ae51d09586b5001ba251f136ca203a9e/lessons/lessons.js#L153-L159

**Comment by KoopReynders** [comment]
Goed dit! (heb het net nog een keer bij een ander issue geschreven - sorry. :)
Zie #4
