### ISSUE TITLE
Code/Design Review

### ISSUE THREAD

**Issue by julia-stevens** [nadiachaja/fix-the-flow-interactive-website#6]
Code review: 
* Je hebt comments geschreven met uitleg van je code
* De variabelen hebben een duidelijke naam
* Je houdt je JS en CSS gescheiden

Design review: 
* _Feedforward:_ Door de pijltjes op de filters weet ik dat ik er op kan klikken. Op je homepagina weet ik dit door 'Let's do it'
*  _Feedback:_ Je hebt verschillende hover animaties en bij een klik gebeurd er iets op de pagina, zoals de resultaten van penguin worden getoond. 
* Misschien kun je nog een `cursor: pointer` toevoegen bij het hamburger menu

Met @OFRqq

**Comment by nadiachaja** [comment]
Ik heb de `cursor: pointer` toegevoegd aan het hamburger menu, ook aan de filter opties en aan de play button om een story te starten
